plugins:
  - '@semantic-release/github'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - prepareCmd: "sed -i -e '/AssemblyVersion/s/>.*</>${nextRelease.version}</' GameJolt.NET/GameJolt.NET.csproj; sed -i -e '/<Version>/s/>.*</>${nextRelease.version}</' GameJolt.NET/GameJolt.NET.csproj"
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: "Unity/Packages/se.hertzole.gamejolt.net"
  - - '@semantic-release/git'
    - assets:
        - "GameJolt.NET/GameJolt.NET.csproj"
        - "CHANGELOG.md"
        - 'Unity/Packages/se.hertzole.gamejolt.net/package.json'