name: Test and Sync Unity Project

on:
  push:
    paths:
      - ".github/workflows/**"
      - "GameJolt.NET/**"
      - "GameJolt.NET.Tests/**"
      - "Unity/**"
      - "ci/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  net_test:
    name: Test .NET
    uses: ./.github/workflows/net_test.yml

  unity-sync:
    name: Sync Unity Project
    uses: ./.github/workflows/unity-sync.yml
    secrets:
      unity_license: ${{ secrets.UNITY_LICENSE }}
      access_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      cache_key: LibraryFolder

  unity-test:
    name: Test Unity Project
    needs: unity-sync
    uses: ./.github/workflows/unity-test.yml
    strategy:
      matrix:
        unity-version:
          - 2021.3.33f1
          - 2022.3.15f1
          - 2023.2.3f1
    secrets:
      unity_license: ${{ secrets.UNITY_LICENSE }}
      unity_email: ${{ secrets.UNITY_EMAIL }}
      unity_password: ${{ secrets.UNITY_PASSWORD }}
      access_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      unity_version: ${{ matrix.unity-version }}
      test_results_name: "Test Results - Unity ${{ matrix.unity-version }}"

  sonarcloud:
    name: SonarScan
    needs: [unity-test, net_test]
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      unity_license: ${{ secrets.UNITY_LICENSE }}
      access_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
    with:
      cache_key: LibraryFolder
      unity_container: unityci/editor:ubuntu-2022.3.15f1-base-3.0.0
      net_test_reports: ${{ needs.net_test.outputs.test_results }}
